#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

exit 0
# Format and submit code according to lintstagedrc.js configuration
# before-commit not eslint
# npm run lint:lint-staged
